apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: python-test-ingress
  namespace: python-test
  labels:
    app: python-test
  annotations:
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: "python-test-cratislab-prod-k8s-aws.cratis.cc"  
    http:
      paths:
      - pathType: Prefix
        path: /      
        backend:
          service: 
            name: python-test
            port:
              number: 80
