apiVersion: v1
kind: Secret
metadata:
  name: regcred
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2RvY2tlci1yZWdpc3RyeS5jcmF0aXMuY2MiOnsidXNlcm5hbWUiOiJhZG1pbiIsInBhc3N3b3JkIjoiTkJeXHUwMDNjeiNaTkZ9PTJ+M35tUC1naiIsImF1dGgiOiJZV1J0YVc0NlRrSmVQSG9qV2s1R2ZUMHlmak4rYlZBdFoybz0ifX19
type: kubernetes.io/dockerconfigjson

