apiVersion: apps/v1
kind: Deployment
metadata:
  name: marker-app
  namespace: marker-app
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: marker-app
  template:
    metadata:
      labels:
        app: marker-app
    spec:
      volumes:
      - name: marker-app
        persistentVolumeClaim:
         claimName: marker-app
      containers:
      - image: k8s.gcr.io/git-sync/git-sync:v3.5.0
        name: install-git-app-data
        volumeMounts:
        - name: marker-app
          mountPath: /usr/local/apache2/htdocs
        env:
          - name: GIT_SYNC_REPO
            value: https://gitlab1.cratis.cc/devops/_marker_app.git
          - name: GIT_SYNC_BRANCH
            value: "master"
          - name: GIT_SYNC_ROOT
            value: "/usr/local/apache2/htdocs/"
          - name: GIT_SYNC_DEST
            value: "_marker_app"
          - name: GIT_SYNC_DEPTH
            value: "1"
          - name: GIT_SYNC_ONE_TIME
            value: "false"
          - name: GIT_SYNC_USERNAME
            value: "tforko"
          - name: GIT_SYNC_PASSWORD
            valueFrom:
             secretKeyRef:
              key: GIT_SYNC_PASSWORD
              name: git-creds