apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: marker-mpbigbang-mysql
  namespace: marker-mpbigbang
spec:
  replicas: 1
  serviceName: marker-mpbigbang-mysql
  selector:
    matchLabels:
      app: marker-mpbigbang-mysql
  template:
    metadata:
      labels:
        app: marker-mpbigbang-mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: marker-mpbigbang-mysql
          image: mysql:8.0
          ports:
            - name: tpc
              protocol: TCP
              containerPort: 3306
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: MYSQL_ROOT_PASSWORD
                name: marker-mpbigbang-mysql-secret        
            - name: MYSQL_DATABASE
              value: mpbigbang
            - name: MYSQL_USER
              value: dev_user
            - name: MYSQL_PASSWORD
              valueFrom: 
               secretKeyRef: 
                key: MYSQL_PASSWORD
                name: marker-mpbigbang-mysql-secret       
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: csi-cephfs-sc
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
