apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: marker-php
  name: hpa-marker-php
  labels:
    app: marker-php
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: marker-php
  targetCPUUtilizationPercentage: 50
  
