apiVersion: apps/v1
kind: Deployment
metadata:
  name: marker-php
spec:
  replicas: 2
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: marker-php
  template:
    metadata:
      labels:
        app: marker-php
    spec:
      containers:
      - image: docker-registry.cratis.cc/cratis/marker-php
        name: marker-php
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 300m
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom: 
             secretKeyRef: 
              key: MYSQL_ROOT_PASSWORD
              name: mysql-secret        
          - name: MYSQL_DATABASE
            value: mpbigbang
          - name: MYSQL_USER
            value: dev_user
          - name: MYSQL_PASSWORD
            valueFrom: 
             secretKeyRef: 
              key: MYSQL_PASSWORD
              name: mysql-secret
      imagePullSecrets:
      - name: regcred

